### PR TITLE
GROUND flow glitch fix

### PR DESCRIPTION
**Pull request by M1XT3NZ**
Wait forgot to test in panorama mode. I hate myself

//edit
Works also with -panorama

### CODE REVIEW

**Comment by namazso** [comment]
Please test this on panorama, especially on de_cache. I haven't pushed my latest changes because i couldn't get it work perfectly. Considering switching to Present hook if this doesnt work

**Comment by M1XT3NZ** [comment]
yeah i actually forgot one file at the moment im testing a bit and then im editing this. give me around 30 minutes

**Comment by M1XT3NZ** [comment]
so in imgui_impl_dx9.cpp line 63 you need to change it to this too
if (g_pd3dDevice->CreateStateBlock(D3DSBT_PIXELSTATE, &d3d9_state_block) < 0)
then it works on cache. I did not see any texture glitches on it.
you need to change that in imgui because when you open the nskinz menu the texture bug will appear again.

**Comment by M1XT3NZ** [comment]
Dude this github for real... i dont even want to commit this to this pull request..

**Comment by M1XT3NZ** [comment]
So just tested on normal mm servers. Works perfectly just imgui_impl_dx9.cpp needs that little update too and all good.

**Comment by M1XT3NZ** [comment]
Oh damn didnt wanted to close that pull request...

**Comment by M1XT3NZ** [comment]
So tried around 6 games with it and no texture bugs anymore.. rly took some time but It works... only shitty thing is that thing with the imgur thing. but yeah....

**Pull request closed without merging**
