### PR TITLE
MP5

### PR DESCRIPTION
**Pull request by M1XT3NZ**
Just added the mp5

### CODE REVIEW

**Comment by namazso** [comment]
The enum is supposed to be in incrementing value order, and the name vector in abc order. Could you fix that?

**Comment by namazso** [comment]
Also, both values are definition indexes so aren't they sopposed to be the same?

**Comment by M1XT3NZ** [comment]
Never heard of them be the same and ups sry for messing with the abc order
I will fix that

**Comment by M1XT3NZ** [comment]
Also i tested it before i pushed it ;) the mp5 + skins work

**Comment by namazso** [comment]
Yea, the enum values are just never used anywhere except that of knives and gloves. I think you mixed it up with classids? Could you fix that? Aince if it works that means the enum should also say 23

**Comment by M1XT3NZ** [comment]
Oh yeah I did ah sry dude I’m really tired my brain isn’t working

**Comment by M1XT3NZ** [comment]
Should not work on some projects when im really tired ...

**Pull request merged**
